ARG BASE_IMAGE=ekidd/rust-musl-builder:latest

# Our first FROM statement declares the build environment.
FROM ${BASE_IMAGE} AS builder

# Add our source code.
ADD ./src/ ./src/
ADD Cargo.toml .
ADD Cargo.lock .
ADD rust-toolchain.toml .

# Fix permissions on source code.
RUN sudo chown -R rust:rust /home/rust

# Build our application.
RUN cargo build --release

# Now, we need to build our _real_ Docker container.
FROM alpine:latest
WORKDIR /home/rust/
RUN apk --no-cache add ca-certificates
COPY --from=builder \
    /home/rust/src/target/x86_64-unknown-linux-musl/release/cubic_storage \
    /usr/local/bin/

HEALTHCHECK --interval=30s --timeout=3s CMD curl -f http://localhost:8080/ || exit 1

CMD /usr/local/bin/cubic_storage
